// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app" | "/app/analytics" | "/app/gateways" | "/app/invoices" | "/app/settings" | "/app/tone" | "/contact" | "/godview" | "/godview/dashboard" | "/login" | "/onboarding/step-1" | "/onboarding/step-2" | "/onboarding/step-3" | "/pricing" | "/privacy" | "/refund" | "/signup" | "/terms"
type AppRouteHandlerRoutes = "/api/webhooks/dodo" | "/api/webhooks/stripe" | "/auth/confirm"
type PageRoutes = "/AcceptInvitation" | "/ComingSoon" | "/Contact" | "/ForgotPassword" | "/Home" | "/Login" | "/NotFound" | "/Pricing" | "/ResetPassword" | "/Signup" | "/admin/AdminDashboard" | "/admin/AdminLogin" | "/admin/AdminRoute" | "/app/Analytics" | "/app/Assistant" | "/app/Dashboard" | "/app/Gateways" | "/app/Invoices" | "/app/Settings" | "/app/ToneStudio" | "/legal/PrivacyPolicy" | "/legal/RefundPolicy" | "/legal/TermsOfService" | "/onboarding/Step1Gateway" | "/onboarding/Step2Tone" | "/onboarding/Step3Sync"
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/AcceptInvitation": {}
  "/admin/AdminDashboard": {}
  "/admin/AdminLogin": {}
  "/admin/AdminRoute": {}
  "/api/webhooks/dodo": {}
  "/api/webhooks/stripe": {}
  "/app": {}
  "/app/analytics": {}
  "/app/Analytics": {}
  "/app/Assistant": {}
  "/app/Dashboard": {}
  "/app/gateways": {}
  "/app/Gateways": {}
  "/app/invoices": {}
  "/app/Invoices": {}
  "/app/settings": {}
  "/app/Settings": {}
  "/app/tone": {}
  "/app/ToneStudio": {}
  "/auth/confirm": {}
  "/ComingSoon": {}
  "/contact": {}
  "/Contact": {}
  "/ForgotPassword": {}
  "/godview": {}
  "/godview/dashboard": {}
  "/Home": {}
  "/legal/PrivacyPolicy": {}
  "/legal/RefundPolicy": {}
  "/legal/TermsOfService": {}
  "/login": {}
  "/Login": {}
  "/NotFound": {}
  "/onboarding/step-1": {}
  "/onboarding/step-2": {}
  "/onboarding/step-3": {}
  "/onboarding/Step1Gateway": {}
  "/onboarding/Step2Tone": {}
  "/onboarding/Step3Sync": {}
  "/pricing": {}
  "/Pricing": {}
  "/privacy": {}
  "/refund": {}
  "/ResetPassword": {}
  "/signup": {}
  "/Signup": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
